/**
 * T3-CUSTOM(expbkt3): Memorable codenames for worktrees.
 *
 * A worktree's on-disk identity is a random hex token (`t3code-2d633e64`), which
 * is unreadable in a sidebar and unusable in conversation. This module maps a
 * worktree path to a short, memorable name drawn from world cities, overflowing
 * into dish names.
 *
 * The mapping is a pure function of the path, so no field has to be added to the
 * thread shell, nothing has to be persisted, and every client — server, web,
 * mobile — derives the same name for the same worktree without coordinating.
 */

/** Longest codename the pool may contain. Sized to fit the sidebar's checkout chip. */
export const WORKTREE_CODENAME_MAX_LENGTH = 10;

/** Number of color buckets a codename can map to. */
export const WORKTREE_CODENAME_TONE_COUNT = 12;

/**
 * Shape every pool entry must satisfy: lowercase ASCII, single token, 3-10 chars.
 * Keeping to this alphabet means a codename is simultaneously safe as a path
 * segment, a git ref fragment, and a URL component — which is what lets Phase 2
 * name the directory itself without a second sanitizing pass.
 */
export const WORKTREE_CODENAME_SHAPE = /^[a-z][a-z0-9]{2,9}$/;

/**
 * Words a codename may never be, because they read as git or filesystem
 * concepts rather than as a name.
 */
export const WORKTREE_CODENAME_RESERVED_WORDS: readonly string[] = [
  "main",
  "master",
  "dev",
  "head",
  "origin",
  "local",
  "node",
  "dist",
  "build",
  "t3code",
  "worktree",
];

/**
 * How many leading characters two codenames may not share. `boston` and `bolton`
 * next to each other in a crowded sidebar are a misreading waiting to happen, so
 * the pool is curated to keep only one of any such pair.
 */
export const WORKTREE_CODENAME_PREFIX_DISTINCTION = 4;

/**
 * Short, ASCII, single-token city names from every populated continent. This is
 * the primary pool; dishes only come into play once it is exhausted.
 */
export const WORKTREE_CITY_CODENAMES = [
  "lisbon",
  "porto",
  "madrid",
  "sevilla",
  "granada",
  "valencia",
  "malaga",
  "bilbao",
  "zaragoza",
  "girona",
  "vigo",
  "oviedo",
  "murcia",
  "alicante",
  "cordoba",
  "toledo",
  "segovia",
  "cadiz",
  "huelva",
  "burgos",
  "palma",
  "ibiza",
  "lleida",
  "cuenca",
  "avila",
  "soria",
  "teruel",
  "ronda",
  "evora",
  "braga",
  "coimbra",
  "faro",
  "aveiro",
  "setubal",
  "leiria",
  "viseu",
  "sintra",
  "paris",
  "lyon",
  "marseille",
  "toulouse",
  "nantes",
  "rennes",
  "bordeaux",
  "nice",
  "cannes",
  "dijon",
  "reims",
  "rouen",
  "nancy",
  "metz",
  "brest",
  "tours",
  "angers",
  "limoges",
  "avignon",
  "annecy",
  "grenoble",
  "perpignan",
  "calais",
  "amiens",
  "caen",
  "orleans",
  "poitiers",
  "biarritz",
  "arles",
  "london",
  "bristol",
  "leeds",
  "york",
  "bath",
  "oxford",
  "norwich",
  "exeter",
  "derby",
  "hull",
  "ipswich",
  "cardiff",
  "swansea",
  "newport",
  "belfast",
  "dublin",
  "galway",
  "limerick",
  "cork",
  "sligo",
  "glasgow",
  "aberdeen",
  "dundee",
  "stirling",
  "inverness",
  "berlin",
  "munich",
  "hamburg",
  "cologne",
  "bonn",
  "mainz",
  "erfurt",
  "jena",
  "kiel",
  "essen",
  "bremen",
  "dresden",
  "leipzig",
  "weimar",
  "trier",
  "fulda",
  "passau",
  "augsburg",
  "bamberg",
  "koblenz",
  "aachen",
  "rostock",
  "potsdam",
  "vienna",
  "graz",
  "linz",
  "salzburg",
  "innsbruck",
  "bregenz",
  "zurich",
  "basel",
  "geneva",
  "bern",
  "luzern",
  "lugano",
  "chur",
  "davos",
  "zermatt",
  "amsterdam",
  "rotterdam",
  "utrecht",
  "leiden",
  "delft",
  "haarlem",
  "arnhem",
  "tilburg",
  "nijmegen",
  "groningen",
  "eindhoven",
  "breda",
  "brussels",
  "antwerp",
  "ghent",
  "bruges",
  "namur",
  "liege",
  "leuven",
  "mons",
  "ostend",
  "aarhus",
  "odense",
  "aalborg",
  "roskilde",
  "oslo",
  "bergen",
  "tromso",
  "stavanger",
  "alesund",
  "bodo",
  "narvik",
  "alta",
  "molde",
  "malmo",
  "uppsala",
  "orebro",
  "umea",
  "lund",
  "vasteras",
  "kiruna",
  "visby",
  "helsinki",
  "turku",
  "tampere",
  "vaasa",
  "oulu",
  "espoo",
  "porvoo",
  "akureyri",
  "tallinn",
  "tartu",
  "parnu",
  "riga",
  "jurmala",
  "vilnius",
  "kaunas",
  "klaipeda",
  "warsaw",
  "krakow",
  "gdansk",
  "poznan",
  "wroclaw",
  "lublin",
  "lodz",
  "torun",
  "sopot",
  "zakopane",
  "katowice",
  "szczecin",
  "prague",
  "brno",
  "plzen",
  "olomouc",
  "ostrava",
  "liberec",
  "kosice",
  "zilina",
  "nitra",
  "presov",
  "budapest",
  "debrecen",
  "szeged",
  "pecs",
  "gyor",
  "eger",
  "miskolc",
  "sopron",
  "ljubljana",
  "maribor",
  "bled",
  "koper",
  "piran",
  "ptuj",
  "zagreb",
  "split",
  "zadar",
  "rijeka",
  "pula",
  "osijek",
  "sibenik",
  "dubrovnik",
  "varazdin",
  "belgrade",
  "nis",
  "subotica",
  "sarajevo",
  "mostar",
  "tuzla",
  "podgorica",
  "kotor",
  "budva",
  "niksic",
  "skopje",
  "ohrid",
  "bitola",
  "tetovo",
  "tirana",
  "durres",
  "vlora",
  "shkoder",
  "sofia",
  "plovdiv",
  "varna",
  "ruse",
  "pleven",
  "vidin",
  "cluj",
  "timisoara",
  "iasi",
  "brasov",
  "sibiu",
  "constanta",
  "oradea",
  "arad",
  "bacau",
  "craiova",
  "galati",
  "ploiesti",
  "suceava",
  "chisinau",
  "balti",
  "kyiv",
  "lviv",
  "odesa",
  "kharkiv",
  "dnipro",
  "poltava",
  "uzhhorod",
  "minsk",
  "gomel",
  "vitebsk",
  "grodno",
  "moscow",
  "kazan",
  "samara",
  "sochi",
  "omsk",
  "perm",
  "tomsk",
  "ufa",
  "tver",
  "kursk",
  "oryol",
  "pskov",
  "tyumen",
  "irkutsk",
  "voronezh",
  "volgograd",
  "yaroslavl",
  "athens",
  "patras",
  "rhodes",
  "chania",
  "volos",
  "larissa",
  "corfu",
  "kavala",
  "ioannina",
  "sparta",
  "delphi",
  "naxos",
  "paros",
  "milos",
  "hydra",
  "kos",
  "istanbul",
  "izmir",
  "ankara",
  "bursa",
  "antalya",
  "konya",
  "adana",
  "trabzon",
  "mersin",
  "kayseri",
  "samsun",
  "urfa",
  "mardin",
  "bodrum",
  "fethiye",
  "rome",
  "milan",
  "naples",
  "turin",
  "venice",
  "florence",
  "bologna",
  "genoa",
  "verona",
  "padua",
  "parma",
  "siena",
  "pisa",
  "lecce",
  "bari",
  "catania",
  "palermo",
  "rimini",
  "ravenna",
  "perugia",
  "ancona",
  "modena",
  "udine",
  "cagliari",
  "messina",
  "livorno",
  "valletta",
  "mdina",
  "nicosia",
  "limassol",
  "paphos",
  "larnaca",
  "cairo",
  "luxor",
  "aswan",
  "giza",
  "tanta",
  "suez",
  "tunis",
  "sousse",
  "sfax",
  "kairouan",
  "bizerte",
  "algiers",
  "oran",
  "annaba",
  "marrakesh",
  "fes",
  "tangier",
  "agadir",
  "meknes",
  "ouarzazate",
  "benghazi",
  "omdurman",
  "gondar",
  "mekelle",
  "nairobi",
  "mombasa",
  "kisumu",
  "nakuru",
  "eldoret",
  "kampala",
  "jinja",
  "entebbe",
  "kigali",
  "butare",
  "dodoma",
  "arusha",
  "mwanza",
  "zanzibar",
  "lusaka",
  "ndola",
  "kitwe",
  "harare",
  "bulawayo",
  "mutare",
  "gaborone",
  "maun",
  "windhoek",
  "maputo",
  "beira",
  "nampula",
  "luanda",
  "lobito",
  "huambo",
  "accra",
  "kumasi",
  "tamale",
  "takoradi",
  "lagos",
  "abuja",
  "kano",
  "ibadan",
  "enugu",
  "jos",
  "dakar",
  "thies",
  "bamako",
  "timbuktu",
  "abidjan",
  "bouake",
  "conakry",
  "kankan",
  "freetown",
  "monrovia",
  "kpalime",
  "niamey",
  "ndjamena",
  "douala",
  "yaounde",
  "bafoussam",
  "libreville",
  "kinshasa",
  "goma",
  "toamasina",
  "curepipe",
  "durban",
  "pretoria",
  "soweto",
  "knysna",
  "george",
  "kimberley",
  "polokwane",
  "rustenburg",
  "amman",
  "aqaba",
  "petra",
  "irbid",
  "byblos",
  "sidon",
  "tyre",
  "baalbek",
  "damascus",
  "aleppo",
  "homs",
  "latakia",
  "baghdad",
  "basra",
  "mosul",
  "erbil",
  "najaf",
  "karbala",
  "tehran",
  "shiraz",
  "isfahan",
  "tabriz",
  "mashhad",
  "yazd",
  "kerman",
  "qom",
  "rasht",
  "riyadh",
  "jeddah",
  "mecca",
  "medina",
  "dammam",
  "abha",
  "taif",
  "doha",
  "dubai",
  "sharjah",
  "ajman",
  "fujairah",
  "muscat",
  "salalah",
  "nizwa",
  "sur",
  "kuwait",
  "manama",
  "sanaa",
  "aden",
  "taiz",
  "kabul",
  "herat",
  "kandahar",
  "mazar",
  "lahore",
  "karachi",
  "peshawar",
  "quetta",
  "multan",
  "hunza",
  "gilgit",
  "murree",
  "sialkot",
  "delhi",
  "mumbai",
  "kolkata",
  "chennai",
  "bangalore",
  "hyderabad",
  "pune",
  "jaipur",
  "lucknow",
  "kanpur",
  "nagpur",
  "indore",
  "bhopal",
  "patna",
  "surat",
  "kochi",
  "mysore",
  "madurai",
  "agra",
  "amritsar",
  "goa",
  "shimla",
  "leh",
  "udaipur",
  "jodhpur",
  "ooty",
  "coorg",
  "kathmandu",
  "pokhara",
  "lumbini",
  "chitwan",
  "thimphu",
  "punakha",
  "dhaka",
  "sylhet",
  "khulna",
  "rajshahi",
  "galle",
  "jaffna",
  "negombo",
  "ella",
  "sigiriya",
  "male",
  "yangon",
  "mandalay",
  "bagan",
  "inle",
  "phuket",
  "krabi",
  "pattaya",
  "ayutthaya",
  "sukhothai",
  "hatyai",
  "udon",
  "rayong",
  "huahin",
  "pakse",
  "battambang",
  "hanoi",
  "saigon",
  "danang",
  "hue",
  "hoian",
  "sapa",
  "dalat",
  "vinh",
  "cantho",
  "halong",
  "penang",
  "ipoh",
  "johor",
  "kuching",
  "langkawi",
  "singapore",
  "jakarta",
  "bandung",
  "medan",
  "bali",
  "ubud",
  "lombok",
  "makassar",
  "semarang",
  "solo",
  "padang",
  "beijing",
  "shanghai",
  "xian",
  "guangzhou",
  "shenzhen",
  "hangzhou",
  "nanjing",
  "wuhan",
  "tianjin",
  "qingdao",
  "dalian",
  "harbin",
  "kunming",
  "guilin",
  "lhasa",
  "urumqi",
  "suzhou",
  "xiamen",
  "sanya",
  "luoyang",
  "datong",
  "jinan",
  "hefei",
  "hongkong",
  "macau",
  "taipei",
  "kaohsiung",
  "tainan",
  "taichung",
  "hualien",
  "seoul",
  "busan",
  "incheon",
  "daegu",
  "jeju",
  "gwangju",
  "daejeon",
  "gyeongju",
  "sokcho",
  "jeonju",
  "tokyo",
  "osaka",
  "kyoto",
  "sapporo",
  "nagoya",
  "kobe",
  "fukuoka",
  "sendai",
  "hiroshima",
  "nara",
  "nikko",
  "hakone",
  "kanazawa",
  "okinawa",
  "matsue",
  "takayama",
  "beppu",
  "naha",
  "aomori",
  "niigata",
  "tashkent",
  "bukhara",
  "khiva",
  "nukus",
  "almaty",
  "astana",
  "shymkent",
  "bishkek",
  "osh",
  "dushanbe",
  "khujand",
  "ashgabat",
  "boston",
  "chicago",
  "denver",
  "austin",
  "seattle",
  "houston",
  "dallas",
  "atlanta",
  "miami",
  "phoenix",
  "detroit",
  "memphis",
  "nashville",
  "orlando",
  "tucson",
  "boise",
  "reno",
  "omaha",
  "wichita",
  "tulsa",
  "fresno",
  "albany",
  "buffalo",
  "hartford",
  "raleigh",
  "savannah",
  "charleston",
  "asheville",
  "sedona",
  "juneau",
  "anchorage",
  "honolulu",
  "maui",
  "kona",
  "taos",
  "aspen",
  "bozeman",
  "missoula",
  "duluth",
  "madison",
  "peoria",
  "topeka",
  "mobile",
  "lubbock",
  "laredo",
  "spokane",
  "eugene",
  "salem",
  "olympia",
  "ithaca",
  "provo",
  "ogden",
  "laramie",
  "cheyenne",
  "fargo",
  "bismarck",
  "pierre",
  "helena",
  "boulder",
  "pueblo",
  "toronto",
  "ottawa",
  "montreal",
  "quebec",
  "vancouver",
  "calgary",
  "edmonton",
  "winnipeg",
  "halifax",
  "regina",
  "saskatoon",
  "kelowna",
  "banff",
  "jasper",
  "whistler",
  "guelph",
  "sudbury",
  "moncton",
  "mexico",
  "cancun",
  "merida",
  "oaxaca",
  "tijuana",
  "tulum",
  "queretaro",
  "morelia",
  "toluca",
  "pachuca",
  "durango",
  "culiacan",
  "veracruz",
  "taxco",
  "cholula",
  "havana",
  "trinidad",
  "nassau",
  "ponce",
  "bogota",
  "medellin",
  "cali",
  "cartagena",
  "pereira",
  "manizales",
  "popayan",
  "quito",
  "guayaquil",
  "banos",
  "otavalo",
  "cusco",
  "arequipa",
  "trujillo",
  "iquitos",
  "piura",
  "huaraz",
  "nazca",
  "paracas",
  "lapaz",
  "sucre",
  "potosi",
  "oruro",
  "tarija",
  "valparaiso",
  "concepcion",
  "arica",
  "valdivia",
  "pucon",
  "rosario",
  "mendoza",
  "salta",
  "jujuy",
  "ushuaia",
  "tucuman",
  "neuquen",
  "posadas",
  "asuncion",
  "rio",
  "recife",
  "fortaleza",
  "belem",
  "natal",
  "curitiba",
  "goiania",
  "maceio",
  "aracaju",
  "campinas",
  "olinda",
  "buzios",
  "cayenne",
  "sydney",
  "melbourne",
  "perth",
  "adelaide",
  "hobart",
  "darwin",
  "canberra",
  "geelong",
  "wollongong",
  "townsville",
  "ballarat",
  "bendigo",
  "launceston",
  "mackay",
  "toowoomba",
  "auckland",
  "queenstown",
  "dunedin",
  "rotorua",
  "taupo",
  "napier",
  "nelson",
  "tauranga",
  "wanaka",
  "nadi",
  "apia",
  "noumea",
  "papeete",
  "honiara",
] as const;

/**
 * Overflow pool. Dishes are as memorable as cities and share none of their
 * spellings, so they extend the namespace without weakening it.
 */
export const WORKTREE_DISH_CODENAMES = [
  "ramen",
  "soba",
  "gyoza",
  "sushi",
  "tempura",
  "mochi",
  "miso",
  "donburi",
  "yakitori",
  "kimchi",
  "bibimbap",
  "bulgogi",
  "japchae",
  "laksa",
  "satay",
  "rendang",
  "sambal",
  "padthai",
  "tomyum",
  "somtam",
  "massaman",
  "panang",
  "dimsum",
  "baozi",
  "mapo",
  "congee",
  "wonton",
  "hotpot",
  "biryani",
  "samosa",
  "dosa",
  "idli",
  "vada",
  "korma",
  "tikka",
  "naan",
  "paneer",
  "chaat",
  "jalebi",
  "halwa",
  "pakora",
  "tandoori",
  "vindaloo",
  "lassi",
  "kebab",
  "shawarma",
  "falafel",
  "hummus",
  "baklava",
  "dolma",
  "manti",
  "borek",
  "meze",
  "pilaf",
  "tagine",
  "couscous",
  "harira",
  "msemen",
  "injera",
  "jollof",
  "egusi",
  "suya",
  "fufu",
  "gazpacho",
  "tortilla",
  "jamon",
  "pulpo",
  "pizza",
  "pasta",
  "risotto",
  "gnocchi",
  "lasagna",
  "ravioli",
  "focaccia",
  "pesto",
  "carbonara",
  "arancini",
  "polenta",
  "crepe",
  "quiche",
  "cassoulet",
  "croissant",
  "baguette",
  "souffle",
  "eclair",
  "confit",
  "fondue",
  "raclette",
  "schnitzel",
  "strudel",
  "bratwurst",
  "spaetzle",
  "bigos",
  "zurek",
  "goulash",
  "borscht",
  "blini",
  "pelmeni",
  "gravlax",
  "waffle",
  "crumpet",
  "trifle",
  "poutine",
  "burrito",
  "pozole",
  "ceviche",
  "arepa",
  "empanada",
  "asado",
  "feijoada",
  "poke",
  "kalua",
  "sashimi",
  "teriyaki",
  "katsu",
  "onigiri",
  "natto",
  "edamame",
  "shabu",
  "sukiyaki",
  "unagi",
  "dango",
  "taiyaki",
  "chirashi",
  "nigiri",
  "oyakodon",
  "tonkatsu",
  "chowder",
  "gumbo",
  "jambalaya",
  "cornbread",
  "grits",
  "biscuit",
  "pancake",
  "muffin",
  "donut",
  "brownie",
  "cookie",
  "custard",
  "pudding",
  "sorbet",
  "gelato",
  "sundae",
  "parfait",
  "mousse",
  "ganache",
  "praline",
  "nougat",
  "toffee",
  "fudge",
  "caramel",
  "marzipan",
  "omelette",
  "frittata",
  "souvlaki",
  "tzatziki",
  "gyros",
  "feta",
  "halloumi",
  "tahini",
  "labneh",
  "fattoush",
  "kibbeh",
  "mansaf",
  "maqluba",
  "knafeh",
  "basbousa",
  "bento",
  "ramyeon",
  "hotteok",
  "gimbap",
  "galbi",
  "tteokbokki",
  "adobo",
  "sinigang",
  "lechon",
  "lumpia",
  "nasilemak",
  "roti",
  "murtabak",
  "cendol",
  "kaya",
  "bunbo",
  "banhxeo",
  "momo",
  "thukpa",
  "rajma",
  "poha",
  "upma",
  "uttapam",
  "kheer",
  "barfi",
  "gulab",
  "ladoo",
  "kulfi",
  "rasam",
  "thali",
  "misal",
  "simit",
  "lahmacun",
  "iskender",
  "pide",
  "menemen",
  "kofte",
  "fesenjan",
  "ghormeh",
  "tahdig",
  "lagman",
  "shashlik",
  "khinkali",
  "satsivi",
  "muesli",
  "haggis",
  "colcannon",
  "boxty",
  "bannock",
  "paella",
  "tapas",
  "coxinha",
  "moqueca",
  "vatapa",
  "alfajor",
  "dulce",
  "humita",
  "locro",
  "anticucho",
  "causa",
  "pisco",
  "elote",
  "birria",
  "barbacoa",
  "horchata",
  "flan",
  "sope",
  "tlayuda",
  "cochinita",
  "menudo",
  "esquites",
  "jerk",
  "doubles",
  "callaloo",
  "ackee",
  "mofongo",
  "tostones",
  "ropa",
  "picadillo",
  "sancocho",
  "pupusa",
  "baleada",
  "kitfo",
  "tibs",
  "berbere",
  "bunny",
  "bobotie",
  "biltong",
  "potjie",
  "chakalaka",
  "samp",
  "mechoui",
  "zaalouk",
  "banku",
  "waakye",
  "kelewele",
  "moinmoin",
  "akara",
  "ogbono",
] as const;

/**
 * The allocation order: cities first, dishes as overflow. Phase 2 walks this
 * array when probing for a free directory name, so a project exhausts the cities
 * before it ever reaches a dish.
 */
export const WORKTREE_CODENAMES: readonly string[] = [
  ...WORKTREE_CITY_CODENAMES,
  ...WORKTREE_DISH_CODENAMES,
];

const WORKTREE_CODENAME_LOOKUP: ReadonlySet<string> = new Set(WORKTREE_CODENAMES);

/**
 * A directory that lost a name race carries a numeric suffix (`lisbon-2`). The
 * suffix is part of the worktree's identity, so it is preserved in the label.
 */
const SUFFIXED_CODENAME = /^([a-z][a-z0-9]{2,9})-(\d{1,3})$/;

function fnv1a32(value: string): number {
  let hash = 0x811c9dc5;
  for (let index = 0; index < value.length; index += 1) {
    hash ^= value.charCodeAt(index);
    hash = Math.imul(hash, 0x01000193) >>> 0;
  }
  return hash >>> 0;
}

/**
 * Collapse the cosmetic differences between two spellings of the same path so
 * that a trailing slash or a Windows separator cannot produce a second codename
 * for one worktree.
 */
export function normalizeWorktreePathForCodename(worktreePath: string): string {
  return worktreePath.trim().replace(/\\/g, "/").replace(/\/+$/, "");
}

/** Stable 32-bit hash of a worktree path. Pinned by test so the pool cannot be reordered silently. */
export function worktreeCodenameHash(worktreePath: string): number {
  return fnv1a32(normalizeWorktreePathForCodename(worktreePath));
}

/** Whether a string is exactly a pool entry. */
export function isWorktreeCodename(value: string): boolean {
  return WORKTREE_CODENAME_LOOKUP.has(value);
}

/**
 * Read a codename off a directory name, if it already is one. This is the seam
 * that makes Phase 2 free: once worktree directories are named `lisbon`, the
 * display layer reports the directory's own name instead of re-deriving one,
 * while legacy `t3code-*` directories keep the name derived from their path.
 */
export function worktreeCodenameFromDirectoryName(directoryName: string): string | null {
  const name = directoryName.trim().toLowerCase();
  if (isWorktreeCodename(name)) {
    return name;
  }
  const suffixed = SUFFIXED_CODENAME.exec(name);
  if (suffixed !== null && isWorktreeCodename(suffixed[1]!)) {
    return name;
  }
  return null;
}

/** The codename for a worktree path. Deterministic, and stable across restarts and clients. */
export function resolveWorktreeCodename(worktreePath: string): string {
  const normalized = normalizeWorktreePathForCodename(worktreePath);
  if (normalized.length === 0) {
    return WORKTREE_CODENAMES[0]!;
  }

  const separatorIndex = normalized.lastIndexOf("/");
  const directoryName = separatorIndex === -1 ? normalized : normalized.slice(separatorIndex + 1);
  const fromDirectory = worktreeCodenameFromDirectoryName(directoryName);
  if (fromDirectory !== null) {
    return fromDirectory;
  }

  return WORKTREE_CODENAMES[fnv1a32(normalized) % WORKTREE_CODENAMES.length]!;
}

function worktreeCodenameDiscriminator(normalizedPath: string): string {
  return (fnv1a32(normalizedPath) & 0xff).toString(16).padStart(2, "0");
}

/**
 * Label every path in a rendered set, appending a short discriminator only to
 * the paths that actually collide *within that set*. The pool is finite, so two
 * live worktrees can land on one name; resolving it per-view keeps the common
 * case clean and the rare case unambiguous.
 *
 * Keyed by the caller's original string, so a caller can look up the label with
 * the same `worktreePath` value it passed in.
 */
export function disambiguateWorktreeCodenames(
  worktreePaths: readonly string[],
): ReadonlyMap<string, string> {
  const normalizedByInput = new Map<string, string>();
  const pathsByCodename = new Map<string, Set<string>>();

  for (const worktreePath of worktreePaths) {
    const normalized = normalizeWorktreePathForCodename(worktreePath);
    if (normalized.length === 0) {
      continue;
    }
    normalizedByInput.set(worktreePath, normalized);

    const codename = resolveWorktreeCodename(normalized);
    const bucket = pathsByCodename.get(codename);
    if (bucket === undefined) {
      pathsByCodename.set(codename, new Set([normalized]));
    } else {
      bucket.add(normalized);
    }
  }

  const labels = new Map<string, string>();
  for (const [worktreePath, normalized] of normalizedByInput) {
    const codename = resolveWorktreeCodename(normalized);
    const collides = (pathsByCodename.get(codename)?.size ?? 1) > 1;
    labels.set(
      worktreePath,
      collides ? `${codename}·${worktreeCodenameDiscriminator(normalized)}` : codename,
    );
  }
  return labels;
}

/**
 * Color bucket for a codename, so the same worktree is recognizable without
 * reading the label. Derived from the codename rather than the path so that a
 * disambiguated label keeps the color of the name it is based on.
 */
export function worktreeCodenameToneIndex(codename: string): number {
  return fnv1a32(codename) % WORKTREE_CODENAME_TONE_COUNT;
}
